### ISSUE TITLE
Cannot use Tools on entity which provide a GUI

### ISSUE THREAD

**Issue by guillaumearm** [ben-mkiv/OpenEntity#3]
When I right-click on a villager with a `DNA tool` : 

![image](https://user-images.githubusercontent.com/16897658/40864195-2b32ec40-65f3-11e8-84e5-c1a0f634ba2c.png)

Same thing with other tools : `OpenEntity tool`, `Remote` and `Hotkey`

I can still use a proxy to access to my villager, but with some limitations.

**Comment by ben-mkiv** [comment]
actually it takes the sample and links remotes but doesnt show you the text.

as workaround for using the tool on a villager you can put a hotkey interface on yourself, assign a hotkey and put the OpenEntity Tool in the slot.

anyways... going to fix that in the next update.

**Comment by ben-mkiv** [comment]
bug is fixed with build 20180614
https://minecraft.curseforge.com/projects/openentity/files/2572616
